package assignment2;

/**
 * Sensor Data is the data generated by the sensor
 *
 * @author bonii
 *
 */
public class SensorReading {

	private float humidity;
	private float temperature;

	public SensorReading(float humidity, float temperature) {
		this.humidity = humidity;
		this.temperature = temperature;
	}

	public float getHumidity() {
		return humidity;
	}

	public void setHumidity(float humidity) {
		this.humidity = humidity;
	}

	public float getTemperature() {
		return temperature;
	}

	public void setTemperature(float temperature) {
		this.temperature = temperature;
	}

}
